name: build

on: [push]

env:
  DOTNET_VERSION: '9.0.x'
  BUILD_CONFIGURATION: Release
  PROJECT_PATH: ./ThAmCo.Products
  PUBLISH_PATH: ./myapp
  TESTRESULTS_PATH: ./test-results

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal
      - name: Prepare publication files
        run: dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret in GitHub using Publish Profile
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}